name: CI/CD Frontend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front_end
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.4"

      - name: Install dependencies
        run: flutter pub get

      - name: Run analyzer
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release

      # Upload artifact để tải APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: front_end/build/app/outputs/flutter-apk/app-release.apk
